sonar.projectKey=SUBSTITUIR_grupoX_projecto-demo
sonar.projectName=Projecto Demo - Turma DevOps
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=SUBSTITUIR_ENDERECO_DO_SERVIDOR
sonar.token=SUBSTITUIR_TOKEN_GERADO_NA_INTERFACE
